server:
  port: 8055
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yihongbo123/springcloud_F.git     # 配置git仓库的地址
#          uri: http://172.17.14.150/fintech/configs.git     # 配置git仓库的地址
          search-paths: config                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 757430916@qq.com                                             # git仓库的账号
          password: bobo52464251
    stream:
      kafka:
        binder:
          brokers: 172.18.44.120:9092,172.18.44.81:9092,172.18.44.123:9092
    bus:
      id: ${eureka.instance.instance-id}
      destination: springCloudBus-2.0
  security:
    user:
      name: user
      password: 123456
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
#      defaultZone: http://172.17.14.145:8761/eureka/,http://172.17.14.146:8761/eureka/
      defaultZone: http://172.18.44.120:8761/eureka/
## http://host:port/actuator/bus-refresh，暴露bus-refresh接口
management:
  endpoints:
    web:
      exposure:
        include: ["bus-refresh"]